image: docker:stable

services:
  - docker:dind

stages:
  - build
  - push

variables:
  IMAGE_10_ALPINE_TAG: 10-alpine
  IMAGE_11_ALPINE_TAG: 11-alpine
  IMAGE_ALPINE_TAG: alpine
  IMAGE_LATEST_TAG: latest
  CONTAINER_IMAGE: "git.sitesoft.ru:4567/$CI_PROJECT_PATH"
  DOCKER_DRIVER: overlay2

before_script:
  - apk add --no-cache curl
  - export NOW_TIMESTAMP=$(date +'%Y%m%d%H%M%S')
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN git.sitesoft.ru:4567

images building:
  stage: build
  only:
    refs:
      - master
  script:
    - docker build --tag "$CONTAINER_IMAGE:$IMAGE_10_ALPINE_TAG" -f ./dockerfiles/Dockerfile.10-alpine ./dockerfiles
    - docker build --tag "$CONTAINER_IMAGE:$IMAGE_11_ALPINE_TAG" -f ./dockerfiles/Dockerfile.11-alpine ./dockerfiles
    - docker build --tag "$CONTAINER_IMAGE:$IMAGE_ALPINE_TAG" -f ./dockerfiles/Dockerfile.alpine ./dockerfiles
    - docker build --tag "$CONTAINER_IMAGE:$IMAGE_LATEST_TAG" -f ./dockerfiles/Dockerfile.latest ./dockerfiles

push image (latest):
  stage: push
  only:
    refs:
      - master
  script:
    - docker push "$CONTAINER_IMAGE:$IMAGE_10_ALPINE_TAG"
    - docker push "$CONTAINER_IMAGE:$IMAGE_11_ALPINE_TAG"
    - docker push "$CONTAINER_IMAGE:$IMAGE_ALPINE_TAG"
    - docker push "$CONTAINER_IMAGE:$IMAGE_LATEST_TAG"
